language: python
# ===== Linux ======
os: linux
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
jobs:
  fast_finish: true
  include:
    # ======= OSX ========
    - name: "Python 3.7.5 on OS X"
      os: osx
      # osx_image: xcode12.2  # xcode12.2: Python 3.9.0
      osx_image: xcode10.2  # xcode12.2: Python 3.7.5
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - bash --version
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install bash
        - bash --version
        - python3 --version
        - python3 -m pip install --upgrade pip
        - python3 -m pip install --upgrade pytest-cov
      install:
        - python3 -m pip install --upgrade .[ja]
      script:
        - python3 -m pytest
        - ./test.sh
    # ====== WINDOWS =========
    - name: "Python 3.7.5 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install wget
        - choco install unzip
        - choco install python --version 3.7.5
        - python --version
        - python -m pip install --upgrade pip
        - python -m pip install --upgrade pytest-cov
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        # Tests fail without the env var below
        - PYTHONUTF8=1
      install:
        - python -m pip install --upgrade .[ja]
      script:
        - python -m pytest
        - ./test.sh
before_install:
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade pytest-cov
install:
  - python -m pip install --upgrade .[ja]
script:
  - python3 -m pytest
  - ./test.sh
