name: check-build

on:
  pull_request

jobs:
  check-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: update
        run: sudo apt-get -y update
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-cov
          pip install .[ja]
      - name: Python pytest test suite
        run: python3 -m pytest
      - name: CLI bash test suite
        run: ./test.sh
